// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBigxUPL_MxEt7KirlJQ1KKJN_K3LC0IU4',
    appId: '1:325769956900:web:7fc51e46d3903991ab52b1',
    messagingSenderId: '325769956900',
    projectId: 'sample-dev-project-796a6',
    authDomain: 'sample-dev-project-796a6.firebaseapp.com',
    databaseURL: 'https://sample-dev-project-796a6-default-rtdb.firebaseio.com',
    storageBucket: 'sample-dev-project-796a6.appspot.com',
    measurementId: 'G-78JDJ3G4L1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk0IspAvKS92VlW9-H6-Lyn_w2YjoeWZQ',
    appId: '1:325769956900:android:b414575a482ec17dab52b1',
    messagingSenderId: '325769956900',
    projectId: 'sample-dev-project-796a6',
    databaseURL: 'https://sample-dev-project-796a6-default-rtdb.firebaseio.com',
    storageBucket: 'sample-dev-project-796a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRZyF_FgaTWs2X33iZdaeYNXIZojiGCV0',
    appId: '1:325769956900:ios:7fcc931ee419c242ab52b1',
    messagingSenderId: '325769956900',
    projectId: 'sample-dev-project-796a6',
    databaseURL: 'https://sample-dev-project-796a6-default-rtdb.firebaseio.com',
    storageBucket: 'sample-dev-project-796a6.appspot.com',
    iosClientId: '325769956900-2hsopngea15u6fr838gqv8e1eth1mvtd.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
